services:
  mysql:
    image: mysql:8.0
    container_name: email_signature_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: email_signature_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword" ]
      timeout: 20s
      retries: 10
      interval: 5s

volumes:
  mysql_data:
